quarkus.application.name=feedback-api
quarkus.banner.enabled=false

resend.api.key=${RESEND_API_KEY:your-resend-api-key}
resend.from.email=${FROM_EMAIL:noreply@fiap.com}
resend.admin.email=${ADMIN_EMAIL:admin@example.com}

# Application Insights
# Connection string do Application Insights
applicationinsights.connection.string=${APPLICATIONINSIGHTS_CONNECTION_STRING:InstrumentationKey=your-key}

weekly.report.cron=0 0 9 * * MON

urgencia.critica.threshold=3

quarkus.http.port=8080

quarkus.log.level=INFO

%dev.quarkus.log.category."br.com.fiap".level=DEBUG

%dev.azure.storage.connection-string=UseDevelopmentStorage=true
%test.azure.storage.connection-string=UseDevelopmentStorage=true

%dev.from.email=onboarding@resend.dev
%dev.admin.email=rm367812@fiap.com.br
%test.from.email=onboarding@resend.dev
%test.admin.email=test@fiap.com.br

%dev.applicationinsights.connection-string=
quarkus.hibernate-validator.fail-fast=false
%test.quarkus.http.port=8081